<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net7.0;net48</TargetFrameworks>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Configurations>Debug;Debug32;Debug64;Release</Configurations>
    <AssemblyTitle>Pachyderm_Noise_Control</AssemblyTitle>
    <Product>Pachyderm_Noise_Control</Product>
    <Copyright>Copyright ©  2015</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Ducts - Junctions_.cs" />
    <Compile Remove="Duct_Model_.cs" />
    <Compile Remove="Duct_Model__.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="TaskParallelLibrary" Version="1.0.2856.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Hare">
      <HintPath>..\..\Hare\bin\Release\net7.0\Hare.dll</HintPath>
    </Reference>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="Copy /y &quot;$(TargetDir)$(ProjectName).dll&quot; &quot;%25appdata%25\Grasshopper\Libraries\$(ProjectName).dll&quot;" />
  </Target>
</Project>